version: '3.8'

services:
  myapp:
    image: myapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com/demo
      - SPRING_DATASOURCE_USERNAME=postgres.arxnskiqsczeadxqjcyv
      # Use placeholder for password to inject via secrets
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
secrets:
  db_password:
    external: true
